// src/components/Greeting.svelte
<style>
	/**
	 * Greeting text
	 */
	.greeting {
		margin: 0;
		font-size: 1.8rem;
		font-weight: normal;
		white-space: nowrap;
		text-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
	}

	.greeting--center {
		font-size: 4rem;
		font-weight: bold;
		text-shadow: 0 0 25px rgba(0, 0, 0, 0.3);
	}

	.greeting--blend {
		text-shadow: 0 0 2px rgba(255, 255, 255, 0.7);
	}

	.greeting__name {
		display: inline-block;
		cursor: pointer;
		position: relative;
	}

	.greeting__name--active > .greeting__name__output {
		display: none;
	}

	.greeting__name__input {
		appearance: none;
		border: 0;
		border-bottom: solid 1px white;
		background: transparent;
		color: inherit;
		font-family: inherit;
		line-height: inherit;
		padding: 0;
		margin: 0;
		width: 8ch;
		position: relative;
		display: none;
		top: 0;
	}

	.greeting--center .greeting__name__input {
		font-weight: bold;
	}

	/* need this for empty greeting name */
	.greeting__name__input--empty {
		position: relative;
	}

	.greeting__name__input::placeholder {
		color: rgba(255, 255, 255, 0.8);
	}

	.greeting__name__input:focus {
		outline: 0;
	}

	.greeting__name--active > .greeting__name__input {
		display: inline-block;
	}
</style>

<h1 id="greeting" class="greeting" class:greeting--center="{center}" class:greeting--blend="{blend}">
	<span id="greeting-text">{ greetText } </span>,
	<div
		class="greeting__name"
		class:greeting__name--active="{ isInputActive }"
		on:click|stopPropagation="{handleNameClick}"
	>
		<input
			bind:this="{nameInput}"
			class="greeting__name__input"
			class:greeting__name__input--empty="{isInputEmpty }"
			bind:value="{inputValue}"
			v-click-outside="onInputClickOutside"
			placeholder="gorgeous"
			on:blur="{() => nameInputSubmit()}"
			on:keypress="{handleKeyPress}"
		/>
		<span class="greeting__name__output">{ greetingName }</span>
	</div>
</h1>

<script>
	/* © 2019 Int3ractive.com
	 * @author Thanh Tran
	 */
	import timer from '../stores/timer';

	let greetText = '';
	let greetingName = ''; // should be from store
	let inputValue = '';
	let isInputEmpty = false;
	let isInputActive = true;
	let nameInput = null; //ref

	const { hours } = $timer;

	if (hours < 12) {
		// morning
		greetText = 'Good morning';
	} else if (hours < 18) {
		// afternoon
		greetText = 'Good afternoon';
	} else if (hours < 22) {
		// evening
		greetText = 'Good evening';
	} else {
		greetText = 'Good night';
	}

	function handleKeyPress(event) {
		// enter
		if (event.charCode === 13) {
			nameInputSubmit();
		}
	}

	function handleNameClick(event) {
		isInputActive = true;
		nameInput.focus();
		nameInput.setSelectionRange(0, nameInput.value.length);

		document.addEventListener('click', nameInputSubmit);
	}

	function nameInputSubmit() {
		if (inputValue) {
			isInputActive = false;
			greetingName = inputValue;
		}

		document.removeEventListener('click', nameInputSubmit);
	}

	export let center = false;
	export let blend = false;
</script>

// src/components/Greeting.vue
<template>
<h1 id="greeting" class="greeting">
	<span id="greeting-text">{{ greetText }}</span>,
	<div id="greeting-name" :class="{ greeting__name: true, 'greeting__name--active': inputActive}"
		@click.stop="onNameClick"
	>
		<input :class="{ greeting__name__input: true, 'greeting__name__input--empty': isInputEmpty}"
			v-model="inputValue"
			placeholder="gorgeous"
			@focus="$event.target.select()"
			@blur="commitInput"
			@keyup.enter="commitInput"
		>
		<span class="greeting__name__output">{{ currentName }}</span>
	</div>
</h1>
</template>

<script>
/* © 2019 int3ractive.com
 * @author Thanh
 */
import Store from '../common/Store';

export default {
	name: 'Greeting',
	props: ['lang'],
	data() {
		return {
			greetText: '',
			inputActive: true,
			inputValue: '',
			currentName: '',
		};
	},
	computed: {
		isInputEmpty() {
			return !this.inputValue.trim();
		},
	},
	methods: {
		onNameClick() {
			this.inputActive = true;
			console.log('Name click');
		},

		update() {
			// greeting
			const today = new Date();
			const hour = today.getHours();
			let greetText = '';

			if (hour < 12) {
				// morning
				greetText = 'Good morning';
			} else if (hour < 18) {
				// afternoon
				greetText = 'Good afternoon';
			} else if (hour < 22) {
				// evening
				greetText = 'Good evening';
			} else {
				greetText = 'Good night';
			}

			this.greetText = greetText;
		},

		commitInput(/*event*/) {
			const newName = this.inputValue.trim();
			console.log('commit input:', newName);
			if (newName) {
				this.currentName = newName;
				Store.set('greetingName', newName);
			} else {
				this.currentName = Store.get('greetingName');
			}

			if (this.currentName) {
				this.inputActive = false;
			}

			// TODO: what is vue's way for click outside?
			// document.removeEventListener('click', nameInputSubmit);
		},
	},
	created() {
		const greetingName = Store.get('greetingName');
		if (greetingName) {
			this.currentName = greetingName;
			this.inputValue = greetingName;
			this.inputActive = false;
		}

		Store.subscribe('all', states => {
			console.log('resume greeting name', states);
		});

		Store.subscribe('currentTime', () => {
			this.update();
		});

		this.update();
	},
};
</script>
